version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    container_name: oracle-db
    ports:
      - "1081:1521"
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=CuongDuy123
    restart: always
    expose:
      - 1521
  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=1521
      - DB_HOST=oracle-db
      - DB_SERVICE=ORCLCDB
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ../Frontend
      dockerfile: ../Frontend/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../Frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

networks:
  default:
    driver: bridge
